server:
  port: 8761
#设置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false #设置中心服务器是否作为客户端注册在本服务器上
    fetch-registry: false #检索服务选项,当设置为true 会进行微服务列表检索
#  instance:
#    hostname: localhost

#自我保护模式
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000 #注销微服务实例的时间间隔

